package org.tenkichannel.umbrella.carry.process;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Weather implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Key
	@org.kie.api.definition.type.Label(value = "Weather Condition (Rain, Thunderstorm, Sunny, etc.)")
	private java.lang.String condition;

	public Weather() {
	}

	public java.lang.String getCondition() {
		return this.condition;
	}

	public void setCondition(java.lang.String condition) {
		this.condition = condition;
	}

	public Weather(java.lang.String condition) {
		this.condition = condition;
	}
	
	@Override
    public String toString() {
        return "Weather [condition=" + condition + "]";
    }

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
		org.tenkichannel.umbrella.carry.process.Weather that = (org.tenkichannel.umbrella.carry.process.Weather) o;
		if (condition != null
				? !condition.equals(that.condition)
				: that.condition != null)
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		int result = 17;
		result = 31 * result + (condition != null ? condition.hashCode() : 0);
		return result;
	}

}