FROM openjdk/openjdk-11-rhel8:latest

LABEL maintainer="Ricardo Zanini <ricardozanini@gmail.com>"

COPY target/rain-forecast-process-1.0.0-SNAPSHOT-runner.jar /deployments/rain-forecast-process-1.0.0-SNAPSHOT-runner.jar