FROM quay.io/kiegroup/kogito-quarkus-ubi8:0.4.0

LABEL maintainer="Ricardo Zanini <ricardozanini@gmail.com>"

COPY target/rain-forecast-process-1.0.0-SNAPSHOT-runner /home/kogito/bin/rain-forecast-process-1.0.0-SNAPSHOT-runner