FROM quay.io/kiegroup/kogito-quarkus-ubi8:0.5.1

LABEL maintainer="Ricardo Zanini <ricardozanini@gmail.com>"

RUN mkdir -p /home/kogito/bin/ && chown -R kogito:kogito /home/kogito/bin/
COPY target/rain-forecast-process-1.1.0-runner /home/kogito/bin/rain-forecast-process-1.1.0-runner