package org.tenkichannel.forecast.rain;

import org.tenkichannel.forecast.rain.Weather;
import org.tenkichannel.forecast.rain.Result;

rule "if condition is Rain, set object accordingly"
ruleflow-group "rainConditionCheck"
no-loop 
    when
        $w : Weather ( condition == "Rain" )
        $r : Result ( )
    then
        modify($r) {
            setIsRain(true);
        };
end

rule "if condition is not Rain, set object accordingly"
ruleflow-group "rainConditionCheck"
no-loop 
    when
        $w : Weather ( condition != "Rain" )
        $r : Result ( )
    then
        modify($r) {
            setIsRain(true);
        };
end