FROM openjdk/openjdk-11-rhel8:latest

LABEL maintainer="Ricardo Zanini <ricardozanini@gmail.com>"

COPY target/weather-api-gateway-1.0.0-SNAPSHOT-runner.jar /deployments/weather-api-gateway-1.0.0-SNAPSHOT-runner.jar