FROM registry.redhat.io/openjdk/openjdk-11-rhel8:latest

LABEL maintainer="Ricardo Zanini <ricardozanini@gmail.com>"

COPY target/weather-api-gateway-1.1.0-runner.jar /deployments/weather-api-gateway-1.1.0-runner.jar